### ISSUE TITLE
Can it be used for real person tasks?

### ISSUE THREAD

**Issue by 281LinChenjian** [WU-CVGL/DreamMesh4D#2]
Thank you for your outstanding work. Would it achieve better results if trained on real human action data?

**Comment by lizhiqi49** [comment]
Thanks for your interest in our work! We mainly conduct our experiments on the testing data from [Consistent4D](https://github.com/yanqinJiang/Consistent4D), in where the cases are all synthetic data or simple in-the-wild data. 
For real human data, it may can not present appealing visual quality, since the diffusion prior, Zero123, is trained on synthetic data.
